apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: elastic-fleet-server
spec:
  version: 8.8.1
  kibanaRef:
    name: elastic
  elasticsearchRefs:
    - name: elastic
  mode: fleet
  fleetServerEnabled: true
  deployment:
    replicas: 1
    podTemplate:
      spec:
        serviceAccountName: fleet-server
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        tolerations:
          - effect: NoSchedule
            key: app
            operator: Equal
            value: stateless
        containers:
        - name: agent
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"