apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-ingress
  namespace: cattle-system
spec:
  secretName: rancher-ingress
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - sla.dev.br