apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    email: 
    server: https://acme-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: 
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key